#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

# Optionally provide the INPUT_VERSION_NAME environment variable for being
# able to defer it to the gradle commands.
#
# For example:
# - Terminal usage: `INPUT_VERSION_NAME="1.2.3" ./.sh/runUnitChecks`
# See `config/unit-gradle-checks/action.yml` for workflow usage deferring to the `env` configuration.

find ./.sh -type f -exec shellcheck {} +

# INPUT_VERSION_NAME is empty
if [[ -z "${INPUT_VERSION_NAME}" ]]
then
  echo "Running component checks without environment variables (local development)..."
  ./gradlew \
    :features:dev:internal:componentTestDebug \
    :features:dev:public-api:componentTestDebug \
    :features:error:internal:componentTestDebug \
    :features:handback:internal:componentTestDebug \
    :features:id-check-wrapper:internal:componentTestDebug \
    :features:resume:internal:componentTestDebug \
    :features:resume:public-api:componentTestDebug \
    :features:select-doc:internal:componentTestDebug \
    :libraries:compose-utils:componentTestDebug \
    :libraries:navigation:componentTestDebug \
else
  echo "Running component checks with environment variables (GitHub workflow)..."
  ./gradlew \
:features:dev:internal:componentTestDebug \
    :features:dev:public-api:componentTestDebug \
    :features:error:internal:componentTestDebug \
    :features:handback:internal:componentTestDebug \
    :features:id-check-wrapper:internal:componentTestDebug \
    :features:resume:internal:componentTestDebug \
    :features:resume:public-api:componentTestDebug \
    :features:select-doc:internal:componentTestDebug \
    :libraries:compose-utils:componentTestDebug \
    :libraries:navigation:componentTestDebug \
    -PversionName="${INPUT_VERSION_NAME}"
fi
