#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

# Optionally provide the INPUT_VERSION_NAME environment variable for being
# able to defer them to the gradle commands.
#
# For example:
# - Terminal usage: `INPUT_VERSION_NAME="1.2.3" ./.sh/runUnitChecks`
# See `config/unit-gradle-checks/action.yml` for workflow usage deferring to the `env` configuration.

find ./.sh -type f -exec shellcheck {} +

# INPUT_VERSION_NAME is empty
if [[ -z "${INPUT_VERSION_NAME}" ]]
then
  echo "Running unit checks without environment variables (local development)..."
  ./gradlew \
    :features:config:internal:testDebugUnitTest \
    :features:config:public-api:testDebugUnitTest \
    :features:dev:internal:unitTestDebug \
    :features:error:internal:unitTestDebug \
    :features:handback:internal:unitTestDebug \
    :features:id-check-wrapper:internal:unitTestDebug \
    :features:resume:internal:unitTestDebug \
    :features:select-doc:internal:unitTestDebug \
    :features:session:internal:unitTestDebug \
    :test-wrapper:testDebugUnitTest
else
  echo "Running unit checks with environment variables (GitHub workflow)..."
  ./gradlew \
    :features:config:internal:testDebugUnitTest \
    :features:config:public-api:testDebugUnitTest \
    :features:dev:internal:unitTestDebug \
    :features:error:internal:unitTestDebug \
    :features:handback:internal:unitTestDebug \
    :features:id-check-wrapper:internal:unitTestDebug \
    :features:resume:internal:unitTestDebug \
    :features:select-doc:internal:unitTestDebug \
    :features:session:internal:unitTestDebug \
    :test-wrapper:testDebugUnitTest \
    -PversionName="$VERSION_NAME"
fi