# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      # Check GitHub Action updates weekly
      interval: "weekly"
    commit-message:
      prefix: "build"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      # Check version catalog updates weekly
      interval: "weekly"
    commit-message:
      prefix: "build"
    groups:
      gradle:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
    
