package uk.gov.onelogin.criorchestrator.testwrapper.testfixtures

const val ANOTHER_SCREEN = "Another screen"
const val CHECK_CAN_PROVE_IDENTITY_ANOTHER_WAY = "Check if you can prove your identity another way"
const val CONFIRM_NO_DRIVING_LICENCE = "Confirm you do not have a UK photocard driving licence"
const val CONFIRM = "Confirm"
const val CONTINUE = "Continue"
const val CONTINUE_TO_PROVE_YOUR_IDENTITY = "Continue to prove your identity"
const val DEVELOPER_SETTINGS = "Developer settings"
const val DO_YOU_HAVE_A_DRIVING_LICENCE = "Do you have a UK photocard driving licence?"
const val DO_YOU_HAVE_A_PASSPORT = "Do you have a passport with a biometric chip?"
const val LOADING = "Loading"
const val NO = "No"
const val RETURN_TO_GOVUK_ON_COMPUTER = "Return to GOV.UK on your computer or tablet"
const val START = "Start"
