[versions]
activityCompose = "1.9.3"
agp = "8.7.3"
androidXCoreKtx = "1.15.0"
androidXTest = "1.6.1"
androidXTestJUnit = "1.2.1"
androidXTestOrchestrator = "1.5.1"
appcompat = "1.7.0"
bouncycastle-jdk18on = "1.79"
composeBom = "2024.12.01"
dagger = "2.53.1" # https://github.com/google/dagger/releases
espressoCore = "3.6.1"
junit = "5.11.4"
junitVersion = "4.13.2"
kotlin = "2.1.0"
lifecycleRuntimeKtx = "2.8.7"
material = "1.12.0"

[libraries]
android-build-tool = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCoreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXTestJUnit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidXTest" }
androidx-test-espresso-accessibility = { module = "androidx.test.espresso:espresso-accessibility", version.ref = "espressoCore" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidXTestOrchestrator" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger" }
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
org-bouncycastle-bcutil-jdk18on = { group = "org.bouncycastle", name = "bcutil-jdk18on", version.ref = "bouncycastle-jdk18on" }
org-junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
org-junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
org-junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
org-junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
uk-gov-pipelines-plugins = { module = "uk.gov.pipelines:plugins" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
