package uk.gov.onelogin.criorchestrator.testwrapper.testfixtures

const val ANOTHER_SCREEN = "Another screen"
const val CHECK_CAN_PROVE_IDENTITY_ANOTHER_WAY = "Check if you can prove your identity another way"
const val CONFIRM = "Confirm"
const val CONFIRM_CONTINUE_DRIVING_LICENCE = "Confirm you want to continue with your UK photocard driving licence"
const val CONFIRM_NO_DRIVING_LICENCE = "Confirm you do not have a UK photocard driving licence"
const val CONTINUE = "Continue"
const val CONTINUE_TO_GOVUK = "Continue to the GOV.UK website"
const val CONTINUE_TO_PROVE_YOUR_IDENTITY = "Continue to prove your identity"
const val DEVELOPER_SETTINGS = "Developer settings"
const val DO_YOU_HAVE_A_DRIVING_LICENCE = "Do you have a UK photocard driving licence?"
const val DO_YOU_HAVE_A_PASSPORT = "Do you have a passport with a biometric chip?"
const val LOADING = "Loading"
const val NO = "No"
const val PHOTO_SUBMITTED = "Photo submitted"
const val RETURN_TO_GOVUK_MOBILE = "Return to GOV.UK to finish proving your identity"
const val RETURN_TO_GOVUK_ON_COMPUTER = "Return to GOV.UK on your computer or tablet"
const val SCAN_FACE_WITH_SELFIE_CAMERA = "Scan your face with your selfie camera"
const val SELECT_BIOMETRIC_TOKEN_RESULT = "Select biometric token result"
const val START = "Start"
const val SUBMIT_PHOTO = "Submit photo"
const val SUCCESS = "Success"
const val TAKE_PHOTO_OF_BACK_OF_DRIVING_LICENCE = "Take a photo of the back of your driving licence"
const val TAKE_PHOTO_OF_FRONT_OF_DRIVING_LICENCE = "Take a photo of the front of your driving licence"
const val THIS_IS_THE_PHOTO_YOU_HAVE_TAKEN = "This is the photo you have taken"
const val YES = "Yes"
