name: On Pull Request

on:
  push: # TODO: remove
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout github action
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up git runner
        uses: ./mobile-android-pipelines/actions/setup-runner
        with:
          jdk-version: 21

      - name: Unit Test
        run: ./scripts/testUnit

      - name: Instrumentation test
        run: ./scripts/testInstrumentation

      - name: Clean workspace
        if: ${{ always() }}
        uses: ./mobile-android-pipelines/config/clean-workspace
