name: Upload to GitHub Packages

on:
  workflow_run:
    workflows: [Shared Post Merge steps]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  upload-to-github-packages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      JDK_VERSION: 17
    permissions:
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2